package com.example.demo5.mybatis.model;

public class StudyGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDYGROUP.ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDYGROUP.NUMBER
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDYGROUP.YEAR
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private Integer year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDYGROUP.ID
     *
     * @return the value of PUBLIC.STUDYGROUP.ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDYGROUP.ID
     *
     * @param id the value for PUBLIC.STUDYGROUP.ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDYGROUP.NUMBER
     *
     * @return the value of PUBLIC.STUDYGROUP.NUMBER
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDYGROUP.NUMBER
     *
     * @param number the value for PUBLIC.STUDYGROUP.NUMBER
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDYGROUP.YEAR
     *
     * @return the value of PUBLIC.STUDYGROUP.YEAR
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDYGROUP.YEAR
     *
     * @param year the value for PUBLIC.STUDYGROUP.YEAR
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setYear(Integer year) {
        this.year = year;
    }
}