package com.example.demo5.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.BIRTHDATE
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private String birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDYGROUP_ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    private Long studygroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.BIRTHDATE
     *
     * @return the value of PUBLIC.STUDENT.BIRTHDATE
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.BIRTHDATE
     *
     * @param birthdate the value for PUBLIC.STUDENT.BIRTHDATE
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @return the value of PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @param surname the value for PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDYGROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.STUDYGROUP_ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public Long getStudygroupId() {
        return studygroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDYGROUP_ID
     *
     * @param studygroupId the value for PUBLIC.STUDENT.STUDYGROUP_ID
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    public void setStudygroupId(Long studygroupId) {
        this.studygroupId = studygroupId;
    }
}