package com.example.demo5.mybatis.dao;


import com.example.demo5.entities.StudyGroup;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudyGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDYGROUP
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024 ss
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDYGROUP
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    int insert(StudyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDYGROUP
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    StudyGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDYGROUP
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    List<StudyGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDYGROUP
     *
     * @mbg.generated Sun Mar 17 20:51:49 EET 2024
     */
    int updateByPrimaryKey(StudyGroup record);
}